# Generated by Django 4.2.26 on 2025-11-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABTestVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=128)),
                (
                    "variant",
                    models.CharField(
                        choices=[("A", "Variant A"), ("B", "Variant B")], max_length=1
                    ),
                ),
                ("visited_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-visited_at"],
            },
        ),
    ]
