# Generated by Django 4.2.26 on 2025-12-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_abtestvisit"),
    ]

    operations = [
        migrations.AddField(
            model_name="abtestvisit",
            name="converted",
            field=models.BooleanField(
                default=False, help_text="Whether the user clicked the button"
            ),
        ),
    ]
